title: "Flora Nativa Bahia Blanca"
email: floranativabb@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Fede
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  fede:
    name: Fede
    display_name: Fede
    avatar: 'assets/images/sal.png'
    email: fede.fg13@gmail.com
    instagram: https://www.instagram.com/sembremos_nativas
    description: "Técnico Univ. en Parques y Jardines y fundador de Flora Nativa Bahia Blanca"

# Social
social:
  instagram: https://www.instagram.com/floranativabb/
  facebook: https://www.facebook.com/floranativabb/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
